document.addEventListener("DOMContentLoaded", () => {
  if (document.body.dataset.page !== "admin") return;

  const state = { products: [], categories: [], editingProduct: null, editingCategory: null };
  const $ = (selector) => document.querySelector(selector);
  const all = (selector) => [...document.querySelectorAll(selector)];
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>\"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[character]));
  const slugify = (value) => String(value || "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const notify = (message, type = "success") => { const element = $("#admin-notice"); element.textContent = message === "Product saved successfully." ? "Product saved and published to Render." : message; element.className = `admin-notice is-visible ${type}`; setTimeout(() => element.classList.remove("is-visible"), 4000); };

  async function request(url, options = {}) {
    const headers = options.body instanceof FormData ? {} : { "Content-Type": "application/json" };
    const response = await fetch(url, { credentials: "same-origin", ...options, headers: { ...headers, ...(options.headers || {}) } });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.message || "Request failed.");
    if (/^\/api\/admin\/catalog\/products(?:\/\d+)?$/.test(url) && ["POST", "PUT"].includes((options.method || "POST").toUpperCase()) && data.product?.id) {
      await request(`/api/admin/catalog/products/${data.product.id}/publish-live`, { method: "POST" });
    }
    return data;
  }

  function renderCategoryOptions(selected = []) {
    const selectedIds = selected.map(Number);
    $("#product-category-options").innerHTML = state.categories.map((category) => `<label class="admin-check"><input type="checkbox" value="${category.id}" ${selectedIds.includes(category.id) ? "checked" : ""}><span>${escapeHtml(category.name)}</span></label>`).join("") || `<p class="admin-muted">Create a category first.</p>`;
    const editingId = state.editingCategory?.id;
    $("#category-parent").innerHTML = `<option value="">No parent</option>${state.categories.filter((category) => category.id !== editingId).map((category) => `<option value="${category.id}">${escapeHtml(category.name)}</option>`).join("")}`;
    $("#product-filter-category").innerHTML = `<option value="">All categories</option>${state.categories.map((category) => `<option value="${category.id}">${escapeHtml(category.name)}</option>`).join("")}`;
  }

  function renderCategories() {
    const query = $("#category-search").value.trim().toLowerCase();
    const categories = state.categories.filter((category) => category.name.toLowerCase().includes(query));
    $("#category-count").textContent = state.categories.length;
    $("#admin-category-list").innerHTML = categories.length ? `<table class="admin-table"><thead><tr><th>Category</th><th>Parent</th><th>Products</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>${categories.map((category) => `<tr><td><div class="admin-media-cell">${category.image_url ? `<img src="${escapeHtml(category.image_url)}" alt="">` : `<span class="admin-media-placeholder">A</span>`}<div><strong>${escapeHtml(category.name)}</strong><small>${escapeHtml(category.slug)}</small></div></div></td><td>${escapeHtml(category.parent_name || "-")}</td><td>${category.product_count || 0}</td><td><span class="status-pill ${category.active ? "is-active" : "is-muted"}">${category.active ? "Active" : "Inactive"}</span></td><td>${new Date(category.updated_at).toLocaleDateString()}</td><td class="admin-row-actions"><button class="btn--ghost" type="button" data-admin-action="edit-category" data-category-id="${category.id}">Edit</button><button class="btn--danger" type="button" data-admin-action="delete-category" data-category-id="${category.id}">Delete</button></td></tr>`).join("")}</tbody></table>` : `<div class="empty-admin-state"><h3>No categories found.</h3><p>Create a category to organize your catalog.</p></div>`;
  }

  function renderProducts() {
    $("#product-count").textContent = state.products.length;
    $("#admin-product-list").innerHTML = state.products.length ? `<table class="admin-table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Categories</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>${state.products.map((product) => `<tr><td><div class="admin-media-cell"><img src="${escapeHtml(product.image || "")}" alt=""><div><strong>${escapeHtml(product.name)}</strong><small>${escapeHtml(product.sku || "No SKU")}</small></div></div></td><td>${Number(product.salePrice || product.price).toFixed(2)} ${product.salePrice ? `<small class="was-price">${Number(product.price).toFixed(2)}</small>` : ""}</td><td>${product.stock}</td><td>${escapeHtml(product.category_names || product.category || "-")}</td><td><span class="status-pill ${product.status === "published" ? "is-active" : "is-muted"}">${escapeHtml(product.status)}</span></td><td>${new Date(product.updated_at).toLocaleDateString()}</td><td class="admin-row-actions"><button class="btn--ghost" type="button" data-admin-action="edit-product" data-product-id="${product.id}">Edit</button><button class="btn--ghost" type="button" data-admin-action="publish-live" data-product-id="${product.id}">Publish live</button><button class="btn--danger" type="button" data-admin-action="delete-product" data-product-id="${product.id}">Archive</button></td></tr>`).join("")}</tbody></table>` : `<div class="empty-admin-state"><h3>No products found.</h3><p>Add your first product to begin curating the shop.</p></div>`;
  }

  async function loadCategories() { const data = await request(`/api/admin/categories?search=${encodeURIComponent($("#category-search").value)}`); state.categories = data.categories || []; renderCategoryOptions(); renderCategories(); }
  async function loadProducts() { const params = new URLSearchParams({ search: $("#product-search").value, category_id: $("#product-filter-category").value, stock_status: $("#product-filter-stock").value }); const data = await request(`/api/admin/catalog/products?${params}`); state.products = data.products || []; renderProducts(); }
  const setValue = (id, value) => { const element = $(`#${id}`); if (element) element.value = value ?? ""; };
  function resetProductForm() { state.editingProduct = null; $("#product-form").reset(); $("#product-id").value = ""; $("#product-form-title").textContent = "Add product"; $("#product-publish-live").disabled = true; $("#product-image-preview").innerHTML = ""; $("#product-video-preview").innerHTML = ""; $("#product-video-urls").innerHTML = ""; renderCategoryOptions(); }
  function closeEditors() { $("#product-editor").hidden = true; $("#category-editor").hidden = true; }
  function preview(url, id, type) { return `<div class="media-item" data-media-id="${id}" data-media-type="${type}">${type === "video" ? `<video src="${escapeHtml(url)}" controls></video>` : `<img src="${escapeHtml(url)}" alt="">`}<button type="button" class="media-remove" data-admin-action="remove-media" data-media-id="${id}" data-media-type="${type}">Remove</button></div>`; }
  function updateDiscount() { const price = Number($("#product-price").value); const sale = Number($("#product-sale-price").value); $("#product-discount").value = price > 0 && sale >= 0 && sale < price ? `${(((price - sale) / price) * 100).toFixed(1)}%` : ""; }
  function openProductEditor(product = null) { resetProductForm(); state.editingProduct = product; $("#product-editor").hidden = false; $("#product-form-title").textContent = product ? `Edit ${product.name}` : "Add product"; if (!product) return; $("#product-publish-live").disabled = false; ["id", "name", "slug", "sku", "status", "price", "salePrice", "stock", "low_stock_threshold", "barcode", "description", "brand", "weight", "dimensions", "meta_title", "meta_description", "meta_keywords"].forEach((field) => setValue(`product-${field === "id" ? "id" : field.replaceAll("_", "-")}`, product[field])); setValue("product-tags", product.tags.join(", ")); renderCategoryOptions(product.category_ids); $("#product-image-preview").innerHTML = product.images.map((image) => preview(image.image_url, image.id, "image")).join(""); $("#product-video-preview").innerHTML = product.videos.map((video) => preview(video.url, video.id, "video")).join(""); updateDiscount(); }
  function openCategoryEditor(category = null) { state.editingCategory = category; $("#category-editor").hidden = false; $("#category-form").reset(); $("#category-form-title").textContent = category ? `Edit ${category.name}` : "Add category"; renderCategoryOptions(); if (category) { setValue("category-id", category.id); setValue("category-name", category.name); setValue("category-slug", category.slug); setValue("category-parent", category.parent_id); setValue("category-active", category.active ? "true" : "false"); setValue("category-description", category.description); $("#category-image-preview").innerHTML = category.image_url ? preview(category.image_url, category.id, "image") : ""; } }
  function addVideoUrl() { const row = document.createElement("div"); row.className = "dynamic-row"; row.innerHTML = `<input type="url" class="product-video-url" placeholder="https://youtube.com/..." required><button type="button" class="btn--danger" data-admin-action="remove-video-url">Remove</button>`; $("#product-video-urls").append(row); }

  $("#product-name").addEventListener("input", (event) => { if (!$("#product-id").value) $("#product-slug").value = slugify(event.target.value); });
  $("#category-name").addEventListener("input", (event) => { if (!$("#category-id").value) $("#category-slug").value = slugify(event.target.value); });
  $("#product-price").addEventListener("input", updateDiscount); $("#product-sale-price").addEventListener("input", updateDiscount);
  $("#product-search").addEventListener("input", loadProducts); $("#product-filter-category").addEventListener("change", loadProducts); $("#product-filter-stock").addEventListener("change", loadProducts); $("#category-search").addEventListener("input", loadCategories);
  $("#product-images").addEventListener("change", (event) => { $("#product-image-preview").innerHTML = [...event.target.files].map((file) => `<div class="media-item"><img src="${URL.createObjectURL(file)}" alt=""><small>${escapeHtml(file.name)}</small></div>`).join(""); });
  $("#product-videos").addEventListener("change", (event) => { $("#product-video-preview").innerHTML = [...event.target.files].map((file) => `<div class="media-item"><video src="${URL.createObjectURL(file)}" controls></video><small>${escapeHtml(file.name)}</small></div>`).join(""); });

  $("#product-form").addEventListener("submit", async (event) => { event.preventDefault(); const price = Number($("#product-price").value); const sale = $("#product-sale-price").value === "" ? null : Number($("#product-sale-price").value); if (sale !== null && sale > price) return notify("Discounted price cannot exceed the original price.", "error"); const payload = { name: $("#product-name").value.trim(), slug: $("#product-slug").value.trim(), sku: $("#product-sku").value.trim(), status: $("#product-status").value, price, salePrice: sale, stock: Number($("#product-stock").value), lowStockThreshold: $("#product-threshold").value, barcode: $("#product-barcode").value.trim(), description: $("#product-description").value.trim(), categoryIds: all("#product-category-options input:checked").map((input) => Number(input.value)), brand: $("#product-brand").value.trim(), tags: $("#product-tags").value.split(",").map((tag) => tag.trim()).filter(Boolean), weight: $("#product-weight").value, dimensions: $("#product-dimensions").value.trim(), metaTitle: $("#product-meta-title").value.trim(), metaDescription: $("#product-meta-description").value.trim(), metaKeywords: $("#product-meta-keywords").value.trim(), videoUrls: all(".product-video-url").map((input) => input.value.trim()).filter(Boolean), removeImageIds: all("[data-remove-image-id]").map((element) => Number(element.dataset.removeImageId)), removeVideoIds: all("[data-remove-video-id]").map((element) => Number(element.dataset.removeVideoId)) }; const formData = new FormData(); formData.append("product", JSON.stringify(payload)); [...$("#product-images").files].forEach((file) => formData.append("images", file)); [...$("#product-videos").files].forEach((file) => formData.append("videos", file)); try { const endpoint = state.editingProduct ? `/api/admin/catalog/products/${state.editingProduct.id}` : "/api/admin/catalog/products"; const result = await request(endpoint, { method: state.editingProduct ? "PUT" : "POST", body: formData }); notify("Product saved successfully."); await loadProducts(); if (event.submitter?.id === "product-save-another") resetProductForm(); else { state.editingProduct = result.product; $("#product-id").value = result.product.id; $("#product-publish-live").disabled = false; $("#product-form-title").textContent = `Saved: ${result.product.name}`; } } catch (error) { notify(error.message, "error"); } });
  $("#category-form").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(); data.append("name", $("#category-name").value.trim()); data.append("slug", $("#category-slug").value.trim()); data.append("parent_id", $("#category-parent").value); data.append("description", $("#category-description").value.trim()); data.append("active", $("#category-active").value); if ($("#category-image").files[0]) data.append("image", $("#category-image").files[0]); try { const endpoint = state.editingCategory ? `/api/admin/categories/${state.editingCategory.id}` : "/api/admin/categories"; await request(endpoint, { method: state.editingCategory ? "PUT" : "POST", body: data }); notify("Category saved successfully."); await loadCategories(); closeEditors(); } catch (error) { notify(error.message, "error"); } });

  document.addEventListener("click", async (event) => { const button = event.target.closest("[data-admin-action]"); if (!button) return; const action = button.dataset.adminAction; if (action === "new-product") openProductEditor(); if (action === "new-category") openCategoryEditor(); if (["close-editor", "close-category-editor"].includes(action)) closeEditors(); if (action === "add-video-url") addVideoUrl(); if (action === "remove-video-url") button.closest(".dynamic-row").remove(); if (action === "edit-product") openProductEditor(state.products.find((product) => product.id === Number(button.dataset.productId))); if (action === "edit-category") openCategoryEditor(state.categories.find((category) => category.id === Number(button.dataset.categoryId))); if (action === "remove-media") { const item = button.closest(".media-item"); item.dataset[button.dataset.mediaType === "image" ? "removeImageId" : "removeVideoId"] = button.dataset.mediaId; item.remove(); } if (action === "publish-live" || action === "publish-current") { const productId = button.dataset.productId || $("#product-id").value; if (!productId) return notify("Save the product before publishing it live.", "error"); try { notify("Publishing product to Render..."); await request(`/api/admin/catalog/products/${productId}/publish-live`, { method: "POST" }); notify("Product published to Render."); } catch (error) { notify(error.message, "error"); } } if (action === "delete-category" && confirm("Delete this category? It must contain no products.")) { try { await request(`/api/admin/categories/${button.dataset.categoryId}`, { method: "DELETE" }); notify("Category deleted."); await loadCategories(); await loadProducts(); } catch (error) { notify(error.message, "error"); } } if (action === "delete-product" && confirm("Archive this product? It will no longer be published.")) { try { await request(`/api/admin/catalog/products/${button.dataset.productId}`, { method: "DELETE" }); notify("Product archived."); await loadProducts(); } catch (error) { notify(error.message, "error"); } } });
  all("[data-admin-tab]").forEach((tab) => tab.addEventListener("click", () => { all("[data-admin-tab]").forEach((item) => item.classList.toggle("is-active", item === tab)); all("[data-admin-view]").forEach((view) => view.classList.toggle("is-active", view.dataset.adminView === tab.dataset.adminTab)); }));
  Promise.all([loadCategories(), loadProducts()]).catch((error) => notify(error.message, "error"));
});
